# NodeJS
FROM node:19-slim

# Set main folder in docker:
WORKDIR /frontend
# Copy file local to docker:
COPY . .

# Run shell-command in docker before build:
RUN npm install

# Run shell-script:
CMD ["npm", "start"]
# App Port (optional)
EXPOSE 3000

# $ cd /frontend
# $ docker build -t frontend_1 .
# $ docker run -d -p 3000:3000 --name front_1 frontend_1
# Browser: http://localhost:3000